on:
  workflow_call:
    inputs:
      repository:
        description: "Repository which Needed to Deploy (Include '/' )"
        required: false
        default: ""
        type: string
      ref:
        description: "Branch which should be built"
        required: false
        default: 'master'
        type: string
      user_name:
        description: "User Name"
        required: false
        default: "passplease"
        type: string
      ruby_version:
        description: "Ruby version to use"
        required: false
        default: "3.3"
        type: string
      send_email:
        description: "Enable email notification"
        required: true
        default: "false"
        type: string
    secrets:
      email_username:
        required: false
      email_password:
        required: false
      email_recipient:
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Template
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.user_name }}/Chirpy-Template
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          # submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Checkout Post
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.user_name }}${{ inputs.repository }}
          sparse-checkout: Chirpy
          path: _temp
          fetch-depth: 0

      - name: Flatten to root
        run: |
          rsync -a _temp/ ./  # 将内容移动到根目录
          rm -rf _temp        # 删除临时目录
          rsync -a Chirpy/assets/img/ ./assets/img/ # 从img中取出文件
          rsync -a Chirpy/ ./  # 从Chirpy中取出文件
          rm -rf Chirpy        # 删除Chirpy

      - name: After File Structrue Changed
        run: find . -type f

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: npm build
        run: npm install && npm run build

      - name: Build site
        run: bundle exec jekyll b -d "_site${{ inputs.repository }}"
        env:
          JEKYLL_ENV: "production"

      - name: After Build
        run: find . -type f

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site${{ inputs.repository }}"

  deploy:
    environment:
      url: "https://${{ inputs.user_name }}.github.io${{ inputs.repository }}"
      name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Send mail
        if: ${{ inputs.send_email == 'true' }}
        uses: dawidd6/action-send-mail@v4
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{ secrets.email_username }}
          # Optional (recommended) mail server password:
          password: ${{ secrets.email_password }}
          # Required mail subject:
          subject: 新博客上传啦
